name: Access GHA secrets
on:
  push:
    branches: ['main']
jobs:
  access-secrets:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: check python
        run: python main.py
        env:
          OKTA_CLIENT_ID: ${{ secrets.MY_SECRET }}
          EMAIL: ${{ vars.EMAIL }}
    
